In [1]:
import numpy as np

In [2]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [3]:
# Accessing elements
print ridership[1, 3]
print ridership[1:3, 3:5]
print ridership[1, :]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [4]:
# Vectorized operations on rows or columns
print ridership[0, :] + ridership[1, :]
print ridership[:, 0] + ridership[:, 1]

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [5]:
# Vectorized operations on entire arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print a + b

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [6]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on
    the first day, then return the mean riders per day for that station.
    Also return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = np.mean(ridership)
    mean_for_max = np.mean(ridership[:,(np.argmax(ridership[0, :]))])
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

In [7]:
# Building the above function

In [8]:
np.argmax(ridership[0, :])

3

In [9]:
top_day_one = np.argmax(ridership[0, :])
print top_day_one

3


In [10]:
ridership[:,3]

array([   5, 2328, 6461, 4787, 4477, 4979,  496,   27, 4174, 4665])

In [11]:
ridership[:,top_day_one]

array([   5, 2328, 6461, 4787, 4477, 4979,  496,   27, 4174, 4665])

In [12]:
np.mean(ridership[:,top_day_one])

3239.9000000000001

In [13]:
np.mean(ridership[:,(np.argmax(ridership[0, :]))])

3239.9000000000001

In [14]:
np.mean(ridership)

2342.5999999999999

In [18]:
# Udacity Solution Below

def mean_riders_for_max_station2(ridership):
    # Find the station with the maximum riders on the first day
    max_station = ridership[0, :].argmax()

    # Find the mean riders per day for that station
    mean_for_max = ridership[:, max_station].mean()

    # Find the mean ridershi overall for comparison
    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station2(ridership)

(2342.5999999999999, 3239.9000000000001)