In [1]:
import numpy as np

In [2]:
# NumPy axis argument
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
    
print a.sum()
print a.sum(axis=0) # Axis 0 takes sum vertically; Y axis
print a.sum(axis=1) # Axis 1 takes sum horizontally; X axis

45
[12 15 18]
[ 6 15 24]


In [3]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [14]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    # Find the mean ridership per day for each subway station
    station_riders = ridership.mean(axis=0)
    
    # Find the maximum daily ridership and the minimum    
    max_daily_ridership = station_riders.max()
    min_daily_ridership = station_riders.min()
    
    return (max_daily_ridership, min_daily_ridership)

min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

In [6]:
# Building the above function

In [8]:
# Find the mean ridership per day for each subway station
ridership.mean(axis=0)

array([ 1071.2,  2814.9,  2718.8,  3239.9,  1868.2])

In [12]:
# Find the maximum daily ridership and the minimum
station_riders = ridership.mean(axis=0)
print station_riders.max()
print station_riders.min()

3239.9
1071.2
