In [1]:
import numpy as np

In [4]:
# Code snippet 1
a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1])
print a
print b

[2 3 4 5]
[2 3 4 5]


In [5]:
# Code snippet 2
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1])
print a
print b

[2 3 4 5]
[1 2 3 4]


In [6]:
a = np.array([1,2,3,4,5])
slice = a[:3]
slice[0] = 100
print a

[100   2   3   4   5]
